# Generated by Django 4.2.17 on 2024-12-24 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для вопроса', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, help_text='Введите короткое описание', max_length=80, null=True),
        ),
    ]
